name: Docker Image CI

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "master" ]


env:
  SERVICE: counter-app
  REGION: us-east4
  PROJECT_ID: gothic-oven-410701
  IMAGE_NAME: acschandra/counter-app-image-from-ci-cd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_REGISTRY_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: |
        BUILD_NAME_WITH_DOT="${{ env.IMAGE_NAME }} ."
        echo "BUILD_NAME_WITH_DOT : $BUILD_NAME_WITH_DOT"
        docker build -t $BUILD_NAME_WITH_DOT
    - name: Push to dockerhub
      run: |
        BUILD_NAME_WITH_LATEST="${{ env.IMAGE_NAME }}:latest"
        echo "BUILD_NAME_WITH_LATEST : BUILD_NAME_WITH_LATEST"
        docker push $BUILD_NAME_WITH_LATEST

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        # NOTE: If required, update to the appropriate source folder
        # source: ./
        image: ${{ env.IMAGE_NAME }}:latest

      # If required, use the Cloud Run url output in later steps
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}